config/routes.rb
Rails.application.routes.draw do
  resources :histogram, only: [:index, :create] 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "histogram#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/histogram_controller.rb
class HistogramController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    text = histogram_params[:text]
    data = Text.generate_word_count(text)
    respond_to do |format|
      format.html { render :index, locals: { data: } }
    end
  end

  def index
    render :index, locals: { data: [] }
  end

  private

  def histogram_params
    params.permit(:text, :file)
    if params[:file] && File.exist?(params[:file])
      path = params[:file].tempfile.to_path.to_s
      params[:text] = File.read(path)
    end
    params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histogram_helper.rb
module HistogramHelper
end

app/views/histogram/index.html.erb
<div class="container flex-column">
  <div class="container spaced">
    <%= form_with url: histogram_index_path, method: :post do |f| %>
      <div class="field">
        <%= f.label :text_input_area %>
        <%= f.text_area :text, rows: "14", class: "text" %>
      </div>
      <%= f.submit 'Generate graph from text', class: "button" %>
    <% end %>

    <%= form_with url: histogram_index_path, method: :post do |f| %>
      <div class="field">
        <%= f.label :file, "Add a text file", class: "file" %>
        <span id="file-selected">No file has been uploaded</span>
        <%= f.file_field :file, accept: 'text/plain' %>
      </div>
      <%= f.submit 'Generate graph from file', class: "button" %>
    <% end %>
  </div>

  <% if data.length > 0 %>
    <%= bar_chart data, id: "bar-chart", colors: ["#000000", "#ff0000", "#013220", "#00008b", "#FFD700"], width: "90%", height: "#{data.length * 30}px" %>
  <% else %>
    <p class="info"> No data found. Add some through the text input or upload a file! </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Histogram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>